name: CI

on: # controls when the workflow will run
  push: # triggers workflow on push event for main
    branches: [ "main" ]
  pull_request: # triggers workflow on pr event for main
    branches: [ "main" ]
  # workflow_dispatch:  # allows workflow to manually from the Actions tab

# workflow run is made up of job(s) that can run sequentially or in parallel
jobs:
  super-lint: # "super-lint" job that ensures everything adheres to consistent formatting/practices in code 
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.0.0
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  test: 
    name: Run Tests 
    runs-on: ubuntu-latest

    env:
      VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
      VITE_GOOGLE_GEMINI_API_KEY: ${{ secrets.VITE_GOOGLE_GEMINI_API_KEY }}

    steps: 
        - name: Checkout Repository 
          uses: actions/checkout@v4

        - name: Cache node_modules # improve efficiency
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node_modules-
          
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install dependencies 
          run: npm install
          
        - name: Run Tests # run the tests carried out by vitest 
          run: npm test
      
      
  build: # "build" job
    name: Build Project
    runs-on: ubuntu-latest # type of runner that the job will run on
    
    env:
      VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
      VITE_GOOGLE_GEMINI_API_KEY: ${{ secrets.VITE_GOOGLE_GEMINI_API_KEY }}

    steps: # steps represent sequential taks that will be executed as part of this "build" job
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Cache node_modules # improve efficiency
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies # ensure that dependencies are installed
        run: npm install

      - name: Run Build
        run: npm run build
